### PR TITLE
Don't set MaxRate and MaxRateInstance

### LINKED ISSUE #1051: Cannot update or create backend_service backed by a group.
# Config
```hcl
resource "google_compute_backend_service" "lipsum" {
  name        = "tst-bs"
  description = "Hello World 1234"
  port_name   = "http"
  protocol    = "HTTP"

  backend {
    group = "${google_compute_instance_group_manager.foobar.instance_group}"
  }

  health_checks = ["${google_compute_http_health_check.default.self_link}"]
}

resource "google_compute_instance_group_manager" "foobar" {
  name               = "tst-igm"
  instance_template  = "${google_compute_instance_template.foobar.self_link}"
  base_instance_name = "foobar"
  zone               = "us-central1-f"
  target_size        = 1
}

resource "google_compute_instance_template" "foobar" {
  name         = "tst-tpl"
  machine_type = "n1-standard-1"

  network_interface {
    network = "default"
  }

  disk {
    source_image = "debian-8-jessie-v20160803"
    auto_delete  = true
    boot         = true
  }
}

resource "google_compute_http_health_check" "default" {
  name               = "tst-hc"
  request_path       = "/"
  check_interval_sec = 1
  timeout_sec        = 1
}
```

# Error
```sh
* google_compute_backend_service.lipsum: Error creating backend service: googleapi: Error 400: Invalid value for field 'resource.backends[0]': ''. Both maxRate or maxRatePerInstance cannot be set., invalid
```

# Expected behavior

Create my backend service without failing since I am not setting maxRate or maxRatePerInstance.

### PR DESCRIPTION
**Pull request by rosbo**
Fixes #1051.

Fixed the backend service tests and the container tests.

### CODE REVIEW

File: google/resource_compute_backend_service.go [hunk 1]
```diff
@@ -351,11 +351,15 @@ func expandBackends(configured []interface{}) ([]*compute.Backend, error) {
...
 			b.MaxRate = int64(v.(int))
-			b.ForceSendFields = append(b.ForceSendFields, "MaxRate")
+			if b.MaxRate == 0 {
+				b.NullFields = append(b.NullFields, "MaxRate")
+			}
 		}
 		if v, ok := data["max_rate_per_instance"]; ok {
 			b.MaxRatePerInstance = v.(float64)
-			b.ForceSendFields = append(b.ForceSendFields, "MaxRatePerInstance")
+			if b.MaxConnectionsPerInstance == 0 {
```
Comment (danawillow) [inline google/resource_compute_backend_service.go]: Shouldn't this be `MaxRatePerInstance`?

Comment (rosbo) [reply google/resource_compute_backend_service.go]: Ouppsi. Forgot to push my uncommitted changes. Good catch
