### PR TITLE
Switch from protoc_output to protoc_output_base64.

### LINKED ISSUE #1237: gRPC Endpoints configuration is never equal to existing resource
Hi there,

### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
- google_endpoints_service

### Terraform Configuration Files
```hcl
resource "google_endpoints_service" "grpc_service" {
  service_name  = "${local.service_name}"
  project       = "${var.gcloud_project}"
  grpc_config   = "${file("${path.module}/templates/grpc_service_spec.yaml")}"
  protoc_output = "${file("${path.module}/templates/compiled_descriptor_file.pb")}"
}
```

### Debug Output
NA

### Expected Behavior
When applying or planning with the same input data, the resource should not be modified.

### Actual Behavior
The protoc_output field is always modified even if the input file is the same.

### Steps to Reproduce
Create a terraform setup that have a google_endpoints_service resource with a grpc_config and protoc_output.
1. `terraform apply`
2. `terraform apply`

The resource will be modified in step 2 which is not expected

### Important Factoids
Diffed a part of the protoc output that was different. And it looks like the "efbfbd" part changes.
Is there some string handling somewhere that truncates the MSB i each byte if set?
 
```
$ diff -u first  second  | tail -n 2 | sed -e 's,^.,,' | while read line; do echo $line | xxd; done
00000000: 7830 3378 3034 2e78 3031 7831 3278 3034  x03x04.x01x12x04
00000010: efbf bd78 3033 6229 6278 3036 7072 6f74  ...x03b)bx06prot
00000020: 6f33 0a                                  o3.
00000000: 7830 3378 3034 2e78 3031 7831 3278 3034  x03x04.x01x12x04
00000010: 7838 6278 3033 6229 6278 3036 7072 6f74  x8bx03b)bx06prot
00000020: 6f33 0a                                  o3.
```

### PR DESCRIPTION
**Pull request by ndmckinley**
Fixes #1237.

```
make test TEST=./google TESTARGS='-run=TestEndpointsService'
==> Checking that code complies with gofmt requirements...
go test -i ./google || exit 1
echo ./google | \ 
        xargs -t -n4 go test -run=TestEndpointsService -timeout=30s -parallel=4
go test -run=TestEndpointsService -timeout=30s -parallel=4 ./google
ok      github.com/terraform-providers/terraform-provider-google/google 0.014s 
```

```
==> Checking that code complies with gofmt requirements...                     
TF_ACC=1 go test ./google -v -run=TestAccEndpointsService -timeout 120m        
=== RUN   TestAccEndpointsService_basic
=== RUN   TestAccEndpointsService_grpc 
--- PASS: TestAccEndpointsService_basic (63.16s)                               
--- PASS: TestAccEndpointsService_grpc (63.24s)                                
PASS                                                                           
ok      github.com/terraform-providers/terraform-provider-google/google 63.251s
```

### CODE REVIEW

**Comment by ndmckinley** [comment]
Like that?

File: google/resource_endpoints_service.go [hunk 1]
```diff
@@ -111,6 +124,20 @@ func resourceEndpointsService() *schema.Resource {
 	}
 }
 
+func migrateEndpointsService(v int, is *terraform.InstanceState, meta interface{}) (*terraform.InstanceState, error) {
```
Comment (danawillow) [inline google/resource_endpoints_service.go]: Usually we have these in a separate file, which might also be a bit more future-proof for when this file becomes generated.

File: google/resource_endpoints_service.go [hunk 2]
```diff
@@ -111,6 +124,20 @@ func resourceEndpointsService() *schema.Resource {
...
+	if v == 0 {
```
Comment (danawillow) [inline google/resource_endpoints_service.go]: we usually use switch/case statements for this, which are nice since they let you fall through (so if a user is on v0 and the latest one is v2, we can sequentially migrate 0->1 and then 1->2). doesn't quite matter now, but will make it easier to extend later if need be

File: google/resource_endpoints_service.go [hunk 3]
```diff
@@ -193,11 +220,11 @@ func resourceEndpointsServiceUpdate(d *schema.ResourceData, meta interface{}) er
 		source = getOpenAPIConfigSource(openapiConfig.(string))
 	} else {
 		grpcConfig, gok := d.GetOk("grpc_config")
-		protocOutput, pok := d.GetOk("protoc_output")
+		protocOutput, pok := d.GetOk("protoc_output_base64")
```
Comment (danawillow) [inline google/resource_endpoints_service.go]: this should probably still allow using `protoc_output` until the field is totally removed

File: website/docs/r/endpoints_service.html.markdown [hunk 4]
```diff
@@ -35,7 +35,7 @@ The following arguments are supported:
 * `service_name`: (Required) The name of the service.  Usually of the form `$apiname.endpoints.$projectid.cloud.goog`.
 * `openapi_config`: (Optional) The full text of the OpenAPI YAML configuration as described [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).  Either this, or *both* of `grpc_config` and `protoc_output` must be specified.
 * `grpc_config`: (Optional) The full text of the Service Config YAML file (Example located [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/bookstore-grpc/api_config.yaml)).  If provided, must also provide `protoc_output`.  `open_api` config must *not* be provided.
-* `protoc_output`: (Optional) The full contents of the Service Descriptor File generated by protoc.  This should be a compiled .pb file.
+* `protoc_output_base64`: (Optional) The full contents of the Service Descriptor File generated by protoc.  This should be a compiled .pb file, base64-encoded.
```
Comment (danawillow) [inline website/docs/r/endpoints_service.html.markdown]: we usually still keep the old field, but just mark it deprecated.

File: google/resource_endpoints_service.go (hunk 1 above)
Comment (ndmckinley) [reply google/resource_endpoints_service.go]: Done.

File: google/resource_endpoints_service.go (hunk 2 above)
Comment (ndmckinley) [reply google/resource_endpoints_service.go]: Done.

File: google/resource_endpoints_service.go (hunk 3 above)
Comment (ndmckinley) [reply google/resource_endpoints_service.go]: Done.

File: website/docs/r/endpoints_service.html.markdown (hunk 4 above)
Comment (ndmckinley) [reply website/docs/r/endpoints_service.html.markdown]: Done.

**Comment by ndmckinley** [comment]
@rosbo Since Dana's on vacation for the next little while, would you mind reviewing this?

File: google/resource_endpoints_service_migration.go [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+	switch v {
+	case 0:
+		if is.Attributes["protoc_output"] == "" {
+			log.Println("[DEBUG] Nothing to migrate to V1.")
+			return is, nil
+		}
+		is.Attributes["protoc_output_base64"] = base64.StdEncoding.EncodeToString([]byte(is.Attributes["protoc_output"]))
+		is.Attributes["protoc_output"] = ""
+		return is, nil
+	case 1:
```
Comment (rosbo) [inline google/resource_endpoints_service_migration.go]: Why this case?

Comment (ndmckinley) [reply google/resource_endpoints_service_migration.go]: `¯\_(ツ)_/¯`
I guess I wasn't sure that we wouldn't get called with a v1->v1 upgrade, but now that you point it out that's silly.  I'll remove it and run the tests and merge.

**Comment by ndmckinley** [comment]
Tests pass, merging.
