### PR TITLE
Fix order of getting project for storage notification topic

### LINKED ISSUE #1486: google_storage_notification has no 'project' field
`google_storage_notification` has no project field. 
And the only way to make the terraform succeed is to explicitly configure the google provider project in your terraform project. 
it will fail with:
```
Error: Error applying plan:

1 error(s) occurred:

* google_storage_notification.notification: 1 error(s) occurred:

* google_storage_notification.notification: project: required field is not set

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure
```

Which comes from copy & pasting from the official doc.
Also the [Documentation](https://www.terraform.io/docs/providers/google/r/storage_notification.html)
is wrong (    event_types       = ["%s","%s"])

### PR DESCRIPTION
**Pull request by emilymye**
Fixes #1486.

* See if the topic includes the project name before checking config.  
* Also, make documentation use actual constants rather than '%s', since it might be confusing 

Should I add a project field for the topic as well? Worried that if I add it, it will get confused with a project associated with the bucket/notification.

### CODE REVIEW

**Comment by rosbo** [comment]
Can you connect a topic and a storage bucket from different projects?

File: google/resource_storage_notification.go [hunk 1]
```diff
@@ -79,13 +79,16 @@ func resourceStorageNotificationCreate(d *schema.ResourceData, meta interface{})
 
 	bucket := d.Get("bucket").(string)
 
-	project, err := getProject(d, config)
-	if err != nil {
-		return err
+	topicName := d.Get("topic").(string)
+	computedTopicName := getComputedTopicName("", topicName)
```
Comment (rosbo) [inline google/resource_storage_notification.go]: Would that make sense to move this logic inside `getComputedTopicName`?

**Comment by emilymye** [comment]
make testacc TEST=./google TESTARGS='--run="TestAccStorageNotification*"'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./google -v --run="TestAccStorageNotification*" -timeout 120m
=== RUN   TestAccStorageNotification_basic
=== PAUSE TestAccStorageNotification_basic
=== RUN   TestAccStorageNotification_withEventsAndAttributes
=== PAUSE TestAccStorageNotification_withEventsAndAttributes
=== CONT  TestAccStorageNotification_basic
=== CONT  TestAccStorageNotification_withEventsAndAttributes
--- PASS: TestAccStorageNotification_withEventsAndAttributes (12.50s)
--- PASS: TestAccStorageNotification_basic (15.04s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google	15.218s
