### PR TITLE
Only check project if it's not present on the resource.

### LINKED ISSUE #1089: Creating a storage bucket require Compute API
Hi,

With the latest terraform google provider version (1.6.0) it is required to enable the Compute API in order to create a bucket. This doesn't seem right.
With version 1.5.0 or older, this is not needed.

### Terraform Version
terraform 0.11.3
terraform-google-provider 1.6.0

### Affected Resource(s)
- google_storage_bucket

### Terraform Configuration Files
```hcl
resource "google_storage_bucket" "myproject-testbucket" {
  name          = "myproject-testbucket"
  project       = "myproject"
  location      = "EUROPE-WEST1"
  storage_class = "REGIONAL"
  force_destroy = false

  labels = {
    opex = "myteam"
  }

  versioning = {
    enabled = false
  }

}
```
A service account with only bucket admin permissions is used to create the bucket.

### Debug Output
google_storage_bucket.myproject-testbucket: googleapi: Error 403: Access Not Configured. Compute Engine API has not been used in project 1234567679 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1234567679 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

### Expected Behavior
Bucket should have been created. The Storage APIs are enabled (by us), but Compute API is not.

### Actual Behavior
Creation failed with error: Access Not Configured. Compute Engine API has not been used 

### Steps to Reproduce
1. Install version 1.6.0 of terraform google provider
2. use hcl example and configure a google provider with credentials
3. run terraforma apply

### PR DESCRIPTION
**Pull request by ndmckinley**
Fixes #1089 by not requiring compute API unless the project needs to be read.  A bucket / project mapping can't be changed after the fact, so it should be safe, and tests (which cover imports) still pass:

```
TF_ACC=1 go test ./google -v -run=TestAccStorageBucket -timeout 120m
=== RUN   TestAccStorageBucket_basic
=== RUN   TestAccStorageBucket_lowercaseLocation
=== RUN   TestAccStorageBucket_customAttributes
=== RUN   TestAccStorageBucket_lifecycleRules
=== RUN   TestAccStorageBucket_storageClass
=== RUN   TestAccStorageBucket_update
=== RUN   TestAccStorageBucket_forceDestroy
=== RUN   TestAccStorageBucket_versioning
=== RUN   TestAccStorageBucket_logging
=== RUN   TestAccStorageBucket_cors
=== RUN   TestAccStorageBucket_labels
--- PASS: TestAccStorageBucket_basic (1.90s)
--- PASS: TestAccStorageBucket_storageClass (5.11s)
--- PASS: TestAccStorageBucket_customAttributes (4.95s)
--- PASS: TestAccStorageBucket_lifecycleRules (2.01s)
--- PASS: TestAccStorageBucket_lowercaseLocation (4.98s)
--- PASS: TestAccStorageBucket_forceDestroy (12.89s)
--- PASS: TestAccStorageBucket_update (22.06s)
--- PASS: TestAccStorageBucket_cors (10.57s)
--- PASS: TestAccStorageBucket_versioning (10.82s)
--- PASS: TestAccStorageBucket_logging (5.50s)
--- PASS: TestAccStorageBucket_labels (22.60s)
PASS
ok      github.com/terraform-providers/terraform-provider-google/google 29.731s
```

### CODE REVIEW

File: google/resource_storage_bucket.go [hunk 1]
```diff
@@ -406,17 +406,24 @@ func resourceStorageBucketRead(d *schema.ResourceData, meta interface{}) error {
...
-	proj, err := config.clientCompute.Projects.Get(strconv.FormatUint(res.ProjectNumber, 10)).Do()
-	if err != nil {
-		return err
+	// resource response.  However, this requires a call to the Compute API, which
+	// would otherwise not be required for this resource.  So, we're going to
+	// intentionally check whether the project is set *on the resource*.  If it is,
+	// we will not try to fetch the project name.  If it is not, either because
+	// the user intends to use the default provider project, or because the resource
+	// is currently being imported, we will read it from the API.
+	if p, ok := d.GetOk("project"); ok && p != "" {
```
Comment (danawillow) [inline google/resource_storage_bucket.go]: No need to check that p != "", that's what ok means.

Also shouldn't this be checking that project isn't set?

Comment (ndmckinley) [reply google/resource_storage_bucket.go]: Oof, the fact that that made the tests pass makes me nervous.  Adding a new test.

**Comment by ndmckinley** [comment]
Added the test!  Still passes.

File: google/resource_storage_bucket.go [hunk 2]
```diff
@@ -406,17 +406,24 @@ func resourceStorageBucketRead(d *schema.ResourceData, meta interface{}) error {
...
-	if err != nil {
-		return err
+	// resource response.  However, this requires a call to the Compute API, which
+	// would otherwise not be required for this resource.  So, we're going to
+	// intentionally check whether the project is set *on the resource*.  If it is,
+	// we will not try to fetch the project name.  If it is not, either because
+	// the user intends to use the default provider project, or because the resource
+	// is currently being imported, we will read it from the API.
+	if _, ok := d.GetOk("project"); !ok {
+		log.Printf("[DEBUG] Read bucket %v at location %v\n\n", res.Name, res.SelfLink)
```
Comment (danawillow) [inline google/resource_storage_bucket.go]: I think this log statement should stay where it was since it's useful regardless of whether we fetch the project

Comment (ndmckinley) [reply google/resource_storage_bucket.go]: You're right, done.
