### PR TITLE
Fix panic on empty maintenance window

### LINKED ISSUE #1267: terraform crash when creating google_sql_database_instance
using terraform-provider-google checked out and built on 3/28/2018 13:00:00 EST

### Terraform Version
Terraform v0.11.5

### Affected Resource(s)
- google_sql_database_instance

### Terraform Configuration Files
```hcl
resource "google_sql_database_instance" "cloudsqldb" {
  name             = "${var.environment_name}-${var.client}-db-${var.region}"
  region           = "${var.region}"
  database_version = "${var.database_version}"

  settings {
    tier               = "${var.machine_type}"
    maintenance_window = {}
  }
}

resource "google_sql_database" "primary_db" {
  instance = "${google_sql_database_instance.cloudsqldb.name}"
  name     = "${var.db_name}"
}

resource "google_sql_user" "primary_db_user" {
  host     = "%"
  instance = "${google_sql_database_instance.cloudsqldb.name}"
  name     = "${var.db_username}"

  #password = "${var.db_password != "" ? var.db_password : "changeme"}"
}
tfvars:
  environment_name = "staging"
  project          = "my-project"
  region           = "europe-west1"
  zone             = "europe-west1-c"
  machine_type     = "db-n1-standard-4"
  db_name          = "db"
  db_username      = "db_staging"
  db_password      = "changeme"
```

### Debug Output
https://gist.github.com/theothermike/3e78aa38815c944b567f336a288e4e89

### Panic Output
https://gist.github.com/theothermike/3e78aa38815c944b567f336a288e4e89

### Expected Behavior
Not crash.  I ran same configs last week with 0.11.3 against another environment and current terraform-provider-google git (as of 3/18/2018) and it worked

### Actual Behavior
crash

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
the output contains references to a lot of other HCL we use to define the rest of the infra.   I've scrubbed the tfvars gist links of client identifying data

### References

### PR DESCRIPTION
**Pull request by emilymye**
Fixes #1267.

Error happens if maintenance window is given but empty.

### CODE REVIEW

File: google/resource_sql_database_instance.go [hunk 1]
```diff
@@ -569,21 +569,24 @@ func resourceSqlDatabaseInstanceCreate(d *schema.ResourceData, meta interface{})
...
 	}
 
-	if v, ok := _settings["maintenance_window"]; ok && len(v.([]interface{})) > 0 {
-		settings.MaintenanceWindow = &sqladmin.MaintenanceWindow{}
-		_maintenanceWindow := v.([]interface{})[0].(map[string]interface{})
+	if v, ok := _settings["maintenance_window"]; ok {
+		windows := v.([]interface{})
+		if len(windows) > 0 && windows[0] != nil {
+			settings.MaintenanceWindow = &sqladmin.MaintenanceWindow{}
+			window := v.([]interface{})[0].(map[string]interface{})
```
Comment (danawillow) [inline google/resource_sql_database_instance.go]: This can be `window := windows[0].(map[string]interface{})`
