### PR TITLE
Make path_rule Optional in google_url_map's path_matcher block.

### LINKED ISSUE #113: google_compute_url_map: "path_matcher.0.path_rule": required field is not set
_This issue was originally opened by @mattes as hashicorp/terraform#15200. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
- google_compute_url_map

### Terraform Configuration Files
```hcl
resource "google_compute_url_map" "primary" {
  name            = "primary"
  default_service = "${google_compute_backend_service.www.self_link}"

  host_rule {
    hosts = ["www"]
    path_matcher = "www"
  }

  path_matcher {
    name = "www"
    default_service = "${google_compute_backend_service.www.self_link}"
    /* path_rule {
       paths = ["/*"] 
       service = "${google_compute_backend_service.www.self_link}" 
    }
    */
  }
}
```

### Expected Behavior
`google_compute_url_map.path_matcher.path_rule` is optional

### Actual Behavior
Error: 
`google_compute_url_map.primary: "path_matcher.0.path_rule": required field is not set`

### PR DESCRIPTION
**Pull request by rileykarson**
Make path_rule Optional in google_url_map's path_matcher block.

Fixes #113 
@danawillow

### CODE REVIEW

File: google/resource_compute_url_map_test.go [hunk 1]
```diff
@@ -320,3 +347,40 @@ resource "google_compute_url_map" "foobar" {
     }
 }
 `, acctest.RandString(10), acctest.RandString(10), acctest.RandString(10))
+
+func testAccComputeUrlMap_noPathRules(bsName, hcName, umName string) string {
+	return fmt.Sprintf(`
+resource "google_compute_backend_service" "foobar" {
```
Comment (danawillow) [inline google/resource_compute_url_map_test.go]: Can you update the indentation and line up the spacing in these resources?
i.e. for this one:
```
resource "google_compute_backend_service" "foobar" {
    name          = "urlmap-test-%s"
    health_checks = ["${google_compute_http_health_check.zero.self_link}"]
}

File: website/docs/r/compute_url_map.html.markdown [hunk 2]
```diff
@@ -108,50 +106,44 @@ The following arguments are supported:
...
+The `path_matcher` block supports:
 
-* `default_service` - (Required) The URL for the backend service or backend bucket to use if none
-    of the given paths match. See the documentation for formatting the service/bucket
-    URL [here](https://cloud.google.com/compute/docs/reference/latest/urlMaps#pathMatcher.defaultService)
+* `name` - (Required) The name of the `path_matcher` resource.
 
-* `name` - (Required) The name of the `path_matcher` resource. Used by the
-    `host_rule` block above.
+* `default_service` - (Required) The URL or [valid partial url](https://cloud.google.com/compute/docs/reference/latest/urlMaps#pathMatcher.defaultService)
```
Comment (danawillow) [inline website/docs/r/compute_url_map.html.markdown]: If a valid partial url is set, will it return that same partial url on read? my gut says no, in which case we should request the full url to avoid perpetual diffs (or needing to set it to computed).

Comment (rileykarson) [inline website/docs/r/compute_url_map.html.markdown]: Updated.

File: google/resource_compute_url_map_test.go (hunk 1 above)
Comment (rileykarson) [inline google/resource_compute_url_map_test.go]: Done.

File: google/resource_compute_url_map_test.go [hunk 3]
```diff
@@ -129,126 +156,130 @@ func testAccCheckComputeUrlMapExists(n string) resource.TestCheckFunc {
...
+    request_path       = "/"
     check_interval_sec = 1
-    timeout_sec = 1
+    timeout_sec        = 1
 }
 
 resource "google_compute_url_map" "foobar" {
-    name = "urlmap-test-%s"
-	default_service = "${google_compute_backend_service.foobar.self_link}"
+    name            = "urlmap-test-%s"
```
Comment (danawillow) [inline google/resource_compute_url_map_test.go]: Looks like a few of these have spaces instead of tabs, which is messing up the indentation in github

File: google/resource_compute_url_map_test.go [hunk 4]
```diff
@@ -129,126 +156,130 @@ func testAccCheckComputeUrlMapExists(n string) resource.TestCheckFunc {
...
```
Comment (danawillow) [inline google/resource_compute_url_map_test.go]: here oo

File: google/resource_compute_url_map_test.go [hunk 5]
```diff
@@ -129,126 +156,130 @@ func testAccCheckComputeUrlMapExists(n string) resource.TestCheckFunc {
...
```
Comment (danawillow) [inline google/resource_compute_url_map_test.go]: and here

File: google/resource_compute_url_map_test.go [hunk 6]
```diff
@@ -257,66 +288,106 @@ resource "google_compute_url_map" "foobar" {
...
```
Comment (danawillow) [inline google/resource_compute_url_map_test.go]: and here

File: google/resource_compute_url_map_test.go [hunk 7]
```diff
@@ -257,66 +288,106 @@ resource "google_compute_url_map" "foobar" {
...
+
+resource "google_compute_http_health_check" "zero" {
+    name               = "urlmap-test-%s"
+    request_path       = "/"
+    check_interval_sec = 1
+    timeout_sec        = 1
+}
+
+resource "google_compute_url_map" "foobar" {
+    name            = "urlmap-test-%s"
```
Comment (danawillow) [inline google/resource_compute_url_map_test.go]: and here

**Comment by rileykarson** [comment]
@danawillow: Done for all. The test configurations were indented with spaces, so I updated them to tabs like most of our other configurations.
