### PR TITLE
Fix service account key data source name

### LINKED ISSUE #1909: google_service_account_key googleapi: Error 400: Invalid JSON payload received. Unknown name "publicKeyType"
Hi

I'm trying to use terraform to get the `google_service_account_key` for the `google_compute_default_service_account` but when I'm getting the following error message `googleapi: Error 400: Invalid JSON payload received. Unknown name "publicKeyType"` when I `terraform apply`.

### Terraform Version
```
Terraform v0.11.8
+ provider.google v1.14.0
+ provider.kubernetes v1.2.0
+ provider.random v2.0.0
```

### Affected Resource(s)
- google_service_account_key

### Terraform Configuration Files
```hcl
data "google_compute_default_service_account" "default" {}

data "google_service_account_key" "key" {
  service_account_id = "${data.google_compute_default_service_account.default.email}"
  public_key_type    = "TYPE_X509_PEM_FILE"
}

resource "kubernetes_secret" "cloudsql_credentials" {
  type = "Opaque"

  metadata {
    name = "cloudsql-instance-credentials"
  }

  data {
    credentials.json = "${base64decode(data.google_service_account_key.key.private_key)}"
  }
}
```

### Debug Output
```
Error: Error refreshing state: 1 error(s) occurred:

* module.production_kubernetes_cluster.data.google_service_account_key.key: 1 error(s) occurred:

* module.production_kubernetes_cluster.data.google_service_account_key.key: data.google_service_account_key.key: Error reading Service Account Key "projects/-/serviceAccounts/<redacted>-compute@developer.gserviceaccount.com": googleapi: Error 400: Invalid JSON payload received. Unknown name "publicKeyType": Cannot bind query parameter. Field 'publicKeyType' could not be found inrequest message., badRequest
```

### Expected Behavior
The `google_service_account_key` should be fetched so that the `.private_key` can be accessed

### Actual Behavior
JSON error

### Steps to Reproduce
1. `terraform apply`

### PR DESCRIPTION
**Pull request by emilymye**
Fixes #1909

$ make testacc TEST=./google TESTARGS='--run="TestAccDatasourceGoogleServiceAccountKey"'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./google -v --run="TestAccDatasourceGoogleServiceAccountKey" -timeout 120m
=== RUN   TestAccDatasourceGoogleServiceAccountKey_basic
=== PAUSE TestAccDatasourceGoogleServiceAccountKey_basic
=== RUN   TestAccDatasourceGoogleServiceAccountKey_errors
=== PAUSE TestAccDatasourceGoogleServiceAccountKey_errors
=== CONT  TestAccDatasourceGoogleServiceAccountKey_basic
=== CONT  TestAccDatasourceGoogleServiceAccountKey_errors
--- PASS: TestAccDatasourceGoogleServiceAccountKey_errors (14.38s)
--- PASS: TestAccDatasourceGoogleServiceAccountKey_basic (18.11s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google	18.281s

### CODE REVIEW

File: google/data_source_google_service_account_key_test.go [hunk 1]
```diff
@@ -50,7 +94,39 @@ resource "google_service_account_key" "acceptance" {
 	public_key_type = "TYPE_X509_PEM_FILE"
 }
 
+data "google_service_account_key" "acceptance" {
+	name = "${google_service_account_key.acceptance.id}"
```
Comment (danawillow) [inline google/data_source_google_service_account_key_test.go]: I really really want to get us away from the practice of relying on the way an id is shaped, since it limits our availability to change them in the future. I just filed #1927 yesterday about that, but in the meantime, is there something else that would work here?

File: google/data_source_google_service_account_key.go [hunk 2]
```diff
@@ -5,32 +5,29 @@ import (
...
+	"regexp"
 )
 
 func dataSourceGoogleServiceAccountKey() *schema.Resource {
 	return &schema.Resource{
 		Read: dataSourceGoogleServiceAccountKeyRead,
 
 		Schema: map[string]*schema.Schema{
-			"service_account_id": &schema.Schema{
+			"name": {
```
Comment (danawillow) [inline google/data_source_google_service_account_key.go]: docs need updating too

Comment (emilymye) [reply google/data_source_google_service_account_key.go]: fixed!

**Comment by emilymye** [comment]
Reran tests:

$ make testacc TEST=./google TESTARGS='--run="TestAccDatasourceGoogleServiceAccountKey"'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./google -v --run="TestAccDatasourceGoogleServiceAccountKey" -timeout 120m
=== RUN   TestAccDatasourceGoogleServiceAccountKey_basic
=== PAUSE TestAccDatasourceGoogleServiceAccountKey_basic
=== RUN   TestAccDatasourceGoogleServiceAccountKey_errors
=== PAUSE TestAccDatasourceGoogleServiceAccountKey_errors
=== CONT  TestAccDatasourceGoogleServiceAccountKey_basic
=== CONT  TestAccDatasourceGoogleServiceAccountKey_errors
--- PASS: TestAccDatasourceGoogleServiceAccountKey_errors (13.86s)
--- PASS: TestAccDatasourceGoogleServiceAccountKey_basic (17.85s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google

File: google/data_source_google_service_account_key.go [hunk 3]
```diff
@@ -67,3 +70,30 @@ func dataSourceGoogleServiceAccountKeyRead(d *schema.ResourceData, meta interfac
...
+		return "", fmt.Errorf("please do not use both name and deprecated service_account_id fields")
+	}
+
+	fullKeyName := keyName
+	// Key name specified as incorrectly named, deprecated service account ID field
+	if keyName == "" {
+		fullKeyName = keyFromSAId
+	}
+
+	if r.MatchString(fullKeyName) {
```
Comment (danawillow) [inline google/data_source_google_service_account_key.go]: Oh, what about adding a ValidateFunc to "name" so these are caught plan-time? That would let us just return the name a bit early from this if it's set.

File: google/data_source_google_service_account_key_test.go [hunk 4]
```diff
@@ -51,6 +95,38 @@ resource "google_service_account_key" "acceptance" {
 }
 
 data "google_service_account_key" "acceptance" {
-	service_account_id = "${google_service_account_key.acceptance.id}"
+	name = "${google_service_account_key.acceptance.id}"
```
Comment (danawillow) [inline google/data_source_google_service_account_key_test.go]: can you change to `.name` here too?

File: website/docs/d/datasource_google_service_account_key.html.markdown [hunk 5]
```diff
@@ -14,27 +14,27 @@ Get service account public key. For more information, see [the official document
...
-  service_account_id = "${data.google_service_account.myaccount.name}"
-  public_key_type = "TYPE_X509_PEM_FILE"
+resource "google_service_account_key" "mykey" {
+  service_account_id = "${google_service_account.myaccount.name}"
 }
 
-output "mykey_public_key" {
-  value = "${data.google_service_account_key.mykey.public_key}"
+data "google_service_account_key" "mykey" {
+  name = "${google_service_account_key.mykey.name}"
```
Comment (danawillow) [inline website/docs/d/datasource_google_service_account_key.html.markdown]: bleh this example is super contrived, although I don't think there are any other resources that output keys that you could input into the data source so I don't have any other ideas.

Comment (emilymye) [reply website/docs/d/datasource_google_service_account_key.html.markdown]: yeah...yeah.

File: google/data_source_google_service_account_key.go (hunk 3 above)
Comment (emilymye) [reply google/data_source_google_service_account_key.go]: I'm going add ValidateFunc to the schema but also leave this here since interpolated values don't trigger ValidateFunc.

**Comment by emilymye** [comment]
$make testacc TEST=./google TESTARGS='--run="TestAccDatasourceGoogleServiceAccountKey_"'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./google -v --run="TestAccDatasourceGoogleServiceAccountKey_" -timeout 120m
=== RUN   TestAccDatasourceGoogleServiceAccountKey_basic
=== PAUSE TestAccDatasourceGoogleServiceAccountKey_basic
=== RUN   TestAccDatasourceGoogleServiceAccountKey_errors
=== PAUSE TestAccDatasourceGoogleServiceAccountKey_errors
=== CONT  TestAccDatasourceGoogleServiceAccountKey_basic
=== CONT  TestAccDatasourceGoogleServiceAccountKey_errors
--- PASS: TestAccDatasourceGoogleServiceAccountKey_errors (13.75s)
--- PASS: TestAccDatasourceGoogleServiceAccountKey_basic (17.75s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google	17.929s
