### PR TITLE
Relax diff on maintenance_policy.daily_maintenance_window.start_time

### LINKED ISSUE #719: Maintenance windows with 1 digit hour start_time trigger google_container_cluster recreation because of formatting issue
On a GKE cluster for which I manually set up a maintenance window with a starting time at 6h00 before it was available on the google terraform provider, `terraform plan` wants to recreate the cluster because of a formatting issue.

The command that was used to set up the maintenance:

```
# gcloud container clusters update mycluster --zone europe-west1-b --maintenance-window=6:00
```

### Terraform Version

Terraform v0.10.8
google provider v1.2.0

### Affected Resource(s)

- google_container_cluster

### Terraform Configuration Files

```hcl
//GKE cluster
resource "google_container_cluster" "gke_cluster1" {
  name               = "${var.general["project"]}-${var.general["region"]}-cluster1"
  zone               = "${var.general["region"]}-${var.gke["main_zone"]}"
  initial_node_count = "${var.gke["initial_node_count"]}"
  network            = "${var.infra["net0_name"]}"
  subnetwork         = "${var.infra["subnet1_name"]}"

  master_auth {
    username = "${var.gke["username"]}"
    password = "${var.gke["password"]}"
  }

  node_config {
    machine_type = "${var.gke["machine_type"]}"

    oauth_scopes = "${var.gke_oauth_scopes}"
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "6:00"
    }
  }
}
```

### Output

```
      maintenance_policy.#:                                       "1" => "1"                 
      maintenance_policy.0.daily_maintenance_window.#:            "1" => "1"                                                                                                              
      maintenance_policy.0.daily_maintenance_window.0.duration:   "PT4H0M0S" => <computed>                                                                                                
      maintenance_policy.0.daily_maintenance_window.0.start_time: "6:00" => "06:00" (forces new resource)                                                                                 
```

### Expected Behavior

Plan should be empty

### Actual Behavior

Plan announces the destruction/recreation of the GKE cluster.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Trying to pass `6:00` instead of `06:00` is rejected by the google terraform provider:

```
# terraform plan                                                                                                    

Error: module.transport.google_container_cluster.gke_cluster1: "maintenance_policy.0.daily_maintenance_window.0.start_time" ("6:00") must be in the format HH:mm (RFC3399)
```

### References

- Support for this was recently added in #670

### PR DESCRIPTION
**Pull request by michaelbannister**
Fixes #719.
Add a DiffSuppressFunc to start_time.

I can't see if there's a useful way to test this in the unit test and I can't see how I'd trigger this condition through an acceptance test case. Ideas & advice welcome!

### CODE REVIEW

File: google/utils_test.go [hunk 1]
```diff
@@ -93,3 +93,11 @@ func TestIpCidrRangeDiffSuppress(t *testing.T) {
 		}
 	}
 }
+
+func TestRfc3339TimeDiffSuppress(t *testing.T) {
+	old := "2:00"
+	new := "02:00"
+	if rfc3339TimeDiffSuppress("time", old, new, nil) == false {
```
Comment (rosbo) [inline google/utils_test.go]: Add also a test case to make sure it doesn't suppress a diff for the following cases:
2:00 and 3:00
02:00 and 3:00
2:00 and 03:00

I suggest you use a table driven test approach like `TestIpCidrRangeDiffSuppress` in this file.

**Comment by michaelbannister** [comment]
Added more test cases as requested. I've removed my assumption that the 'new' value will always have a two-digit hour, in case that validation restriction gets lifted (or used somewhere else where it's not enforced).

**Comment by rosbo** [comment]
Thanks Michael!
