### PR TITLE
google_compute_instance can specified the subnetwork using a self_link

### LINKED ISSUE #247: Support self_link for network_interface field subnetwork in google_compute_instance for consistency
### Terraform Version
0.10.0

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_network" "network1" {
  name = "network-1" 
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "network1-sub1" {
  name = "network1-sub1"
  ip_cidr_range = "10.128.0.0/20"  
  network = "${google_compute_network.network1.self_link}"
  region = "us-east1"
}

resource "google_compute_instance" "i1" {
  name = "test-instance1"
  machine_type = "f1-micro"
  can_ip_forward = false
  zone = "us-east1-c"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-8"
    }
  }

  network_interface {
    subnetwork = "${google_compute_subnetwork.network1-sub1.self_link}"
  }
}
```

### Expected Behavior
The `google_compute_instance` should have been created.

### Actual Behavior

Fails because the subnetwork can only be reference by name.
`${google_compute_subnetwork.network1-sub1.name}`.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The network field supports both `name` and `self_link`. Supporting both would be more consistent.

### PR DESCRIPTION
**Pull request by rosbo**
Fixes #247 

Currently, you can only specify the `subnetwork` for `google_compute_instance` using the `subnetwork` name. See issue #247 for more context.

This adds the support for both `name` and `self_link` when specifying the `subnetwork` bringing consistency with the way other network/subnetwork fields works.

I also added support for reading the network_interface fields from GCP. 

cc/ @danawillow

### CODE REVIEW

File: google/resource_compute_instance.go [hunk 1]
```diff
@@ -278,20 +279,25 @@ func resourceComputeInstance() *schema.Resource {
...
 					Schema: map[string]*schema.Schema{
 						"network": &schema.Schema{
-							Type:     schema.TypeString,
-							Optional: true,
-							ForceNew: true,
+							Type:             schema.TypeString,
+							Optional:         true,
+							Computed:         true,
+							ForceNew:         true,
+							DiffSuppressFunc: linkDiffSuppress,
```
Comment (danawillow) [inline google/resource_compute_instance.go]: While you're here, want to add a `ConflictsWith` for `subnetwork`? Then we can get rid of an if statement below
