### PR TITLE
Fix error in instance template read.

### LINKED ISSUE #2067: Running the plan with google_compute_instance_template results in an error
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.11.8
+ provider.google v1.18.0
```

### Affected Resource(s)

google_compute_instance_template

### Terraform Configuration Files

```tf
resource "google_compute_instance_template" "instance-01" {
  name           = "instance-01"
  description    = "instance-01"
  can_ip_forward = true
  machine_type   = "n1-standard-1"

  scheduling {
    automatic_restart   = true
    on_host_maintenance = "MIGRATE"
  }

  // Create a new boot disk from an image
  disk {
    source_image = "instance01"
    auto_delete  = true
    boot         = true
    disk_size_gb = 10
  }

  network_interface {
    subnetwork = "${google_compute_subnetwork.intra-network.name}"

    access_config {
      nat_ip = "${google_compute_address.instance-01.address}"
    }
  }

  service_account {
    scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }
}
```

### Expected Behavior

I did not change it.

### Actual Behavior

`terraform plan`

```
* google_compute_instance_template.instance-01: 1 error(s) occurred:

* google_compute_instance_template.instance-01: google_compute_instance_template.instance-01: error flattening disks: Error getting relative path for source image: String was not a self link: global/images/instance01
```

### Important Factoids

The image specified by source_image is an image of an image created by another project.
It is not an image existing by default in GCP.

Also, this google_compute_instance_template is a resource you have already created.

### References

This correction seems to have caused this problem.

* #1916

### PR DESCRIPTION
**Pull request by paddycarver**
Flattening disks involves taking the relative link of each disk. This
only works if you start from a self_link, but we were starting from
anything that resolveImage returns, which includes several
not-self_links.

This PR adds a test that shows the failure, and then fixes it by
expanding the output back out to a self_link before getting the relative
link from it.

Tests with only test changes applied:

```
=== RUN   TestAccComputeInstanceTemplate_imageShorthand
=== PAUSE TestAccComputeInstanceTemplate_imageShorthand
=== CONT  TestAccComputeInstanceTemplate_imageShorthand
--- FAIL: TestAccComputeInstanceTemplate_imageShorthand (59.82s)
    testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:

        * google_compute_instance_template.foobar: 1 error(s) occurred:

        * google_compute_instance_template.foobar: error flattening disks: Error getting relative path for source image: String was not a self link: global/images/test-li6yeo17du
    testing.go:579: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Error refreshing: 1 error(s) occurred:

        * google_compute_instance_template.foobar: google_compute_instance_template.foobar: error flattening disks: Error getting relative path for source image: String was not a self link: global/images/test-li6yeo17du

        State: <nil>
FAIL
FAIL    github.com/terraform-providers/terraform-provider-google/google 59.835s
```

Tests with whole PR applied:

```
=== RUN   TestAccComputeInstanceTemplate_imageShorthand
=== PAUSE TestAccComputeInstanceTemplate_imageShorthand
=== CONT  TestAccComputeInstanceTemplate_imageShorthand
--- PASS: TestAccComputeInstanceTemplate_imageShorthand (93.79s)
PASS
ok      github.com/terraform-providers/terraform-provider-google/google 93.805s
```

Fixes #2067.

### CODE REVIEW

File: google/resource_compute_instance_template.go [hunk 1]
```diff
@@ -683,12 +683,16 @@ func resourceComputeInstanceTemplateCreate(d *schema.ResourceData, meta interfac
...
 }
 
-func flattenDisks(disks []*computeBeta.AttachedDisk, d *schema.ResourceData) ([]map[string]interface{}, error) {
+func flattenDisks(disks []*computeBeta.AttachedDisk, d *schema.ResourceData, defaultProject string) ([]map[string]interface{}, error) {
 	result := make([]map[string]interface{}, 0, len(disks))
 	for _, disk := range disks {
 		diskMap := make(map[string]interface{})
 		if disk.InitializeParams != nil {
-			path, err := getRelativePath(disk.InitializeParams.SourceImage)
+			link, err := resolvedImageSelfLink(defaultProject, disk.InitializeParams.SourceImage)
```
Comment (rileykarson) [inline google/resource_compute_instance_template.go]: nit: s/link/selfLink
