### PR TITLE
Increase IAM custom role length validation to match API.

### LINKED ISSUE #3658: role_id with more than 30 characters doesn't match regexp
### Terraform Version

```
# terraform version
Terraform v0.11.14
+ provider.google v2.6.0
+ provider.google-beta v2.6.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `google_project_iam_custom_role`

### Terraform Configuration Files
```hcl
resource "google_project_iam_custom_role" "storage_object_creator" {
  role_id     = "myproject.cloudStorageObjectCreator"
  title       = "My Project Cloud Storage Object Creator"
  description = "Role to enable object creation access to a Google Cloud Storage Bucket"

  permissions = [
    "storage.objects.create",
  ]
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior
What should have happened?

Configuration should apply fine like in previous versions up to 2.5.1.

### Actual Behavior
What actually happened?

Configuration is rejected:
```
Error: google_project_iam_custom_role.storage_object_creator: "role_id" ("myproject.cloudStorageObjectCreator") doesn't match regexp "^[a-zA-Z0-9_\\.\\-]{1,30}$"
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

N/A

### References

N/A

### PR DESCRIPTION
**Pull request by rremer**
This fixes #3658 @pdecat 

I'm still digging for the doc source which generates this misinformation: https://cloud.google.com/iam/docs/understanding-custom-roles#naming_the_role

### CODE REVIEW

**Comment by rremer** [comment]
Happy to contribute the doc fix too, but was unable to locate the source for it. Left feedback on that page instead to rectify the naming constraints.

File: google/validation.go [hunk 1]
```diff
@@ -29,7 +29,7 @@ const (
 	ComputeServiceAccountNameRegex = "[0-9]{1,20}-compute@developer.gserviceaccount.com"
 
 	// https://cloud.google.com/iam/docs/understanding-custom-roles#naming_the_role
-	IAMCustomRoleIDRegex = "^[a-zA-Z0-9_\\.\\-]{1,30}$"
+	IAMCustomRoleIDRegex = "^[a-zA-Z0-9_\\.\\-]{1,64}$"
```
Comment (pdecat) [inline google/validation.go]: The minimum length is 3 and the dash is not accepted according to [gcloud's output](https://github.com/terraform-providers/terraform-provider-google/issues/3658#issuecomment-494045315):
```suggestion
	IAMCustomRoleIDRegex = "^[a-zA-Z0-9_\\.]{3,64}$"
```

**Comment by hrgui** [comment]
I had the same issues that @pdecat had, but then when I went to the GCP UI, I saw the following:

Screen Shot 2019-05-21 at 10 58 46 AM

There seems to be a disconnect from what the UI is saying and what the API is saying for this validation, and I am wondering if the UI should update to reflect what the API is saying and the docs should be updated too?

**Comment by danawillow** [comment]
Hi @hrgui, each of those components is maintained by a different team, but I went ahead and filed bugs internally so hopefully we'll see an update at some point.

**Comment by danawillow** [comment]
GCP docs have been updated: https://cloud.google.com/iam/docs/understanding-custom-roles#naming_the_role 🎉

**Comment by rremer** [comment]
For the record, is there a repo somewhere we could have made the change to or are those doc sources internal?

**Comment by danawillow** [comment]
It's internal, thanks for trying though!
