### PR TITLE
Fix BackendService group hash when instance groups use beta features

### LINKED ISSUE #462: Backend Service cannot reconsolidate state
When attempting to create a backend service, it is attempting to update said resource after creation. Root cause seems to be that it is unable to consolidate the state from the provider with the local state.

### Terraform Version
Terraform v0.10.6

### Affected Resource(s)
- google_compute_backend_service

### Terraform Configuration Files
```hcl
resource "google_compute_backend_service" "public" {
  name        = "backend-service"
  description = "Some description"
  port_name   = "http"
  protocol    = "HTTP"

  backend {
    balancing_mode  = "UTILIZATION"
    capacity_scaler = 1
    max_utilization = 0.8
    group           = "${google_compute_instance_group_manager.web.instance_group}"
  }

  health_checks = ["${google_compute_http_health_check.default.self_link}"]
}
```
### Expected Behavior

After running `terraform apply` and without making any further changes to the resources then terrafom should report that there are no changes to be made when doing `terraform plan`.

### Actual Behavior

Running `terraform plan` after doing a `terraform apply`. Will produce the following output:

```
  ~ module.swarm_cluster_eu1.google_compute_backend_service.public
      backend.242332812.balancing_mode:        "" => "UTILIZATION"
      backend.242332812.capacity_scaler:       "" => "1"
      backend.242332812.description:           "" => ""
      backend.242332812.group:                 "" => "https://www.googleapis.com/compute/beta/projects/foobar/zones/europe-west1-b/instanceGroups/web"
      backend.242332812.max_rate:              "" => ""
      backend.242332812.max_rate_per_instance: "" => ""
      backend.242332812.max_utilization:       "" => "0.8"
      backend.797817009.balancing_mode:        "UTILIZATION" => ""
      backend.797817009.capacity_scaler:       "1" => "0"
      backend.797817009.description:           "" => ""
      backend.797817009.group:                 "https://www.googleapis.com/compute/v1/projects/foobar/zones/europe-west1-b/instanceGroups/web" => ""
      backend.797817009.max_rate:              "0" => "0"
      backend.797817009.max_rate_per_instance: "0" => "0"
      backend.797817009.max_utilization:       "0.8" => "0"
```

### PR DESCRIPTION
**Pull request by danawillow**
Fixes #462.

The issue in #462 was that `backend.group` takes a self link of an instance group. Instance Group Managers have a beta field, `auto_healing_policies`. If that is set, then its self link will be the beta one since we have to read from the beta API in order to read that field. In that case, the example config ended up such that state had the v1 self link (because it reads from the v1 BackendServices API) but plan wanted to change it to a beta self link (because it reads from the beta InstanceGroupManagers API).

The link of the instance group is one of the factors that makes up the hash for the backend. In order to make sure changes in api version don't impact the backend hash, I've changed it to use the relative path instead of the full self link. Since this changes the value of the hash, I added a state migration.

While I was in the neighborhood, I also changed `group` to Required since it'll fail server-side if it's not set (and our documentation actually says it's Required) and added a self link DiffSuppress for it.

```
$ make testacc TEST=./google TESTARGS='-run=TestComputeBackendServiceMigrateState'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./google -v -run=TestComputeBackendServiceMigrateState -timeout 120m
=== RUN   TestComputeBackendServiceMigrateState
2017/10/03 16:46:42 [INFO] Found Compute Backend Service State v0; migrating to v1
2017/10/03 16:46:42 [DEBUG] Attributes before migration: map[string]string{"backend.242332812.balancing_mode":"UTILIZATION", "backend.242332812.max_utilization":"0.8", "backend.#":"1", "backend.242332812.group":"https://www.googleapis.com/compute/v1/projects/project_name/zones/zone_name/instances/instanceGroups/igName"}
2017/10/03 16:46:42 [DEBUG] Attributes after migration: map[string]string{"backend.2573491210.balancing_mode":"UTILIZATION", "backend.2573491210.max_utilization":"0.8", "backend.2573491210.group":"https://www.googleapis.com/compute/v1/projects/project_name/zones/zone_name/instances/instanceGroups/igName", "backend.#":"1"}
--- PASS: TestComputeBackendServiceMigrateState (0.00s)
=== RUN   TestComputeBackendServiceMigrateState_empty
2017/10/03 16:46:42 [DEBUG] Empty InstanceState; nothing to migrate.
2017/10/03 16:46:42 [DEBUG] Empty InstanceState; nothing to migrate.
--- PASS: TestComputeBackendServiceMigrateState_empty (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google	0.159s
```

```
$ make testacc TEST=./google TESTARGS='-run=TestAccComputeBackendService_withBackend'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./google -v -run=TestAccComputeBackendService_withBackend -timeout 120m
=== RUN   TestAccComputeBackendService_withBackend
--- PASS: TestAccComputeBackendService_withBackend (93.22s)
=== RUN   TestAccComputeBackendService_withBackendAndUpdate
--- PASS: TestAccComputeBackendService_withBackendAndUpdate (105.21s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google	198.636s
```

### CODE REVIEW

File: google/resource_compute_backend_service_migrate.go [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+func migrateBackendServiceStateV0toV1(is *terraform.InstanceState) (*terraform.InstanceState, error) {
+	log.Printf("[DEBUG] Attributes before migration: %#v", is.Attributes)
+
+	oldHashToValue := map[string]map[string]interface{}{}
+	for k, v := range is.Attributes {
+		if !strings.HasPrefix(k, "backend.") {
+			continue
+		}
+
+		if k == "backend.#" {
```
Comment (rosbo) [inline google/resource_compute_backend_service_migrate.go]: You could move it in the if above with a `||`.

File: google/resource_compute_backend_service_migrate_test.go [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+		StateVersion       int
+		Attributes         map[string]string
+		ExpectedAttributes map[string]string
+		Meta               interface{}
+	}{
+		"v0 to v1": {
+			StateVersion: 0,
+			Attributes: map[string]string{
+				"backend.#":                         "1",
+				"backend.242332812.group":           "https://www.googleapis.com/compute/v1/projects/project_name/zones/zone_name/instances/instanceGroups/igName",
```
Comment (rosbo) [inline google/resource_compute_backend_service_migrate_test.go]: You could add also a test with a beta group. Even though it wouldn't add much value I guess...

File: google/resource_compute_backend_service_migrate.go (hunk 1 above)
Comment (danawillow) [reply google/resource_compute_backend_service_migrate.go]: Done

File: google/resource_compute_backend_service_migrate_test.go (hunk 2 above)
Comment (danawillow) [reply google/resource_compute_backend_service_migrate_test.go]: Eh, not going to bother on this one since this test doesn't make any API calls or really look at the version
