### PR TITLE
Fix autoscaler - was unnecessarily forcing to a single metric

### LINKED ISSUE #38: GCE Autoscaler: terraform only lets you select one policy while gce allows multiple, metric target types don't match gce
_This issue was originally opened by @nwwebb as hashicorp/terraform#7614. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Terraform Version:
v0.6.16

Affected Resource:
google_compute_autoscaler

Expected Behavior:
- GCE allows multiple policies to be applied to an autoscaler. The user can specify cpu utilization, load balancing utilization and multiple metrics utilizations if they choose. 
- The  metric utilization target types in GCE are gauge, delta/min, delta/sec.

Actual Behavior:
- Terraform doesn't support multiple policies for an autoscaler in a config file.
- When Terraform attempts to update an autoscaler with a new policy (ex: changing from cpu utilization to load balancer utilization) it creates an autoscaler with both policies.
- The metric utilization target types for a Terraform config file are gauge, delta, cumulative

Steps to Reproduce:

The following resource will cause Terraform to complain because multiple policies are specified, although gce lets the user select multiple policies.

```
resource "google_compute_autoscaler" "foobar" {
  name   = "foobar"
  zone   = "us-central1-f"
  target = "${google_compute_instance_group_manager.foobar.self_link}"

  autoscaling_policy = {
    max_replicas    = 5
    min_replicas    = 1
    cooldown_period = 60

    cpu_utilization {
      target = 0.5
    }
    load_balancer_utilization {
      target = 0.5
  }
}
```

Also, if you were to apply this autoscaler:

```
resource "google_compute_autoscaler" "foobar" {
  name   = "foobar"
  zone   = "us-central1-f"
  target = "${google_compute_instance_group_manager.foobar.self_link}"

  autoscaling_policy = {
    max_replicas    = 5
    min_replicas    = 1
    cooldown_period = 60

    cpu_utilization {
      target = 0.5
    }
  }
}
```

Followed by this: 

```
resource "google_compute_autoscaler" "foobar" {
  name   = "foobar"
  zone   = "us-central1-f"
  target = "${google_compute_instance_group_manager.foobar.self_link}"

  autoscaling_policy = {
    max_replicas    = 5
    min_replicas    = 1
    cooldown_period = 60

    load_balancing_utilization {
      target = 0.5
    }
  }
}
```

Terraform will create an autoscaler with load balancing and cpu utilization set rather than remove the cpu utilization.

@lwander

### PR DESCRIPTION
**Pull request by ndmckinley**
Multiple metrics are supported, as the new test proves.  Also, we weren't successfully storing the right information about custom metrics on read... you can imagine why we didn't catch that since it's a little-used feature.

This fixes #38.

### CODE REVIEW

File: google/resource_compute_autoscaler.go [hunk 1]
```diff
@@ -153,39 +157,30 @@ func buildAutoscaler(d *schema.ResourceData) (*compute.Autoscaler, error) {
...
+			if d.Get(fmt.Sprintf("%smetric.%d.name", prefix, m)) != "" {
+				customMetrics = append(customMetrics, &compute.AutoscalingPolicyCustomMetricUtilization{
+					Metric:                d.Get(fmt.Sprintf("%smetric.%d.name", prefix, m)).(string),
+					UtilizationTarget:     d.Get(fmt.Sprintf("%smetric.%d.target", prefix, m)).(float64),
+					UtilizationTargetType: d.Get(fmt.Sprintf("%smetric.%d.type", prefix, m)).(string),
+				})
 			}
 		}
 	}
+	fmt.Printf("customMetrics: %s\n", customMetrics)
```
Comment (rosbo) [inline google/resource_compute_autoscaler.go]: Remove this debug line

**Comment by ndmckinley** [comment]
```==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./google -v -run=TestAccComputeAutoscaler -timeout 120m
=== RUN   TestAccComputeAutoscaler_basic
=== RUN   TestAccComputeAutoscaler_update
=== RUN   TestAccComputeAutoscaler_multicondition
--- PASS: TestAccComputeAutoscaler_basic (69.14s)
--- PASS: TestAccComputeAutoscaler_multicondition (70.74s)
--- PASS: TestAccComputeAutoscaler_update (82.94s)
PASS
ok      github.com/terraform-providers/terraform-provider-google/google 82.948s
```

**Comment by ndmckinley** [comment]
Oh, and since CI's still behind:
```01:04 $ make
==> Checking that code complies with gofmt requirements...
go install
```
