### PR TITLE
Set default scopes when creating GKE clusters/node pools

### LINKED ISSUE #898: Unable to create a GKE cluster
Reporting the same as in:
https://github.com/hashicorp/terraform/issues/16981

Probably this is more adequate place to put this.

### Terraform Version
```
Terraform v0.11.1
+ provider.google v1.2.0 (but also v1.4.0)
+ provider.random v1.0.0
```

### Terraform Configuration Files

```hcl

resource "google_container_cluster" "the_cluster" {
  name               = "the-cluster-${random_string.the_cluster_id.result}"
  zone               = "europe-west1-c"
  min_master_version = "1.8.4-gke.1"
  initial_node_count = 1

  logging_service    = "none"
  monitoring_service = "none"

  maintenance_policy {
    daily_maintenance_window {
      start_time = "03:00"
    }
  }

  addons_config {
    http_load_balancing {
      disabled = true
    }
  }

  node_config {
    disk_size_gb = "32"
    image_type   = "COS"
    machine_type = "n1-standard-2"
    preemptible  = false

    labels {
      pool    = "default-pool"
      cluster = "the-cluster"
    }
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

*Note*: The error happens also when creating a `google_container_node_pool`

### Expected Behavior

The cluster is created within 15-30 minutes

### Actual Behavior

Error from Google API:  `All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 1 have registered. Cluster may be unhealthy.`

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

Running on the latest version of macOS (High Sierra)

### PR DESCRIPTION
**Pull request by danawillow**
gcloud sets a whole bunch of scopes by default, match that list here. Fixes #898.

### CODE REVIEW

File: google/node_config.go [hunk 1]
```diff
@@ -104,9 +114,15 @@ var schemaNodeConfig = &schema.Schema{
 
 func expandNodeConfig(v interface{}) *container.NodeConfig {
 	nodeConfigs := v.([]interface{})
-	nodeConfig := nodeConfigs[0].(map[string]interface{})
+	nc := &container.NodeConfig{
+		// Defaults can't be set on a list in the schema, so set the default on create here.
```
Comment (rosbo) [inline google/node_config.go]: nit: technically, this is a set not a list.
