### PR TITLE
Fix auto-delete default network in google_project.

### LINKED ISSUE #1331: Error on auto_create_network = false
### Terraform Version
v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- google_project

Hi there,
I'm trying to do the following:
```hcl
resource "google_project" "folder" {
  name                = "pf-test-smoke"
  project_id          = "pf-test-smoke-april13-2"
  org_id              = "${var.org_id}"
  billing_account     = "${var.billing}"
  auto_create_network = "false"
}
```

But when I perform the terraform apply command, it creates the project but throws the following error:

```hcl
google_project.folder: Still creating... (10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* google_project.folder: 1 error(s) occurred:

* google_project.folder: Error deleting network: googleapi: Error 404: Failed to find project pf-test-smoke, notFound

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

I think it's searching project by name and not by id. project_id is "pf-test-smoke-april13-2" but the error says the project's name (pf-test-smoke).

I'm using the last terraform version and the compiled code from this provider.
I've also tested it with folder (not org_id) and fails too.

```hcl
Thanks in advance!
```

### PR DESCRIPTION
**Pull request by rosbo**
- Use ProjectId when calling the APIs instead of the project name
- The compute API has to be enabled before we can delete the network
- The firewall rules inside the default network must be deleted before we delete the network.
- Update documentation to clarify this side effect.

Fixes #1331

### CODE REVIEW

**Comment by rosbo** [comment]
Test is failling because the default network is created with 4 default firewall rules and these have to be deleted before we can delete the network:

```sh
--- FAIL: TestAccProject_deleteDefaultNetwork (118.51s)
    testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:
        
        * google_project.acceptance: 1 error(s) occurred:
        
        * google_project.acceptance: The network resource 'projects/terraform-619kodgqiy/global/networks/default' is already being used by 'projects/terraform-619kodgqiy/global/firewalls/default-allow-rdp'  
```

**Comment by ndmckinley** [comment]
Ah, dang, that's totally my fault for not testing my code.  I see the test failure but I'll take it from here if you like, no reason for you to keep working fixing my mistake.

File: google/resource_compute_network.go [hunk 1]
```diff
@@ -195,9 +195,12 @@ func resourceComputeNetworkDelete(d *schema.ResourceData, meta interface{}) erro
 		return err
 	}
 
-	// Delete the network
+	return deleteComputeNetwork(project, d.Id(), config)
```
Comment (ndmckinley) [inline google/resource_compute_network.go]: You'll still want a d.SetId("") if err == nil, right?

**Comment by rosbo** [comment]
```sh
--- PASS: TestAccProject_deleteDefaultNetwork (206.61s)
```

@ndmckinley tests are passing. PTAL

File: google/resource_compute_network.go (hunk 1 above)
Comment (rosbo) [reply google/resource_compute_network.go]: The `d.SetId("")` is actually redundant: https://github.com/hashicorp/terraform/blob/master/helper/schema/resource.go#L205

Comment (ndmckinley) [reply google/resource_compute_network.go]: I did not know that!
