### PR TITLE
MergeBindings ignores empty bindings.

### LINKED ISSUE #1338: Empty binding members for google_project_iam_policy result in continually changing plan
### Terraform Version

Terraform v0.11.7
+ provider.google v1.9.0

### Affected Resource(s)

- google_project_iam_policy

### Terraform Configuration Files
```hcl
variable "id" {
  default = "XXXXX"
}

variable "owners" {
  default = ["user:user@example.com"]
}

variable "viewers" {
  default = []
}

data "google_iam_policy" "policy" {
  binding {
    role    = "roles/owner"
    members = ["${var.owners}"]
  }

  binding {
    role    = "roles/viewer"
    members = ["${var.viewers}"]
  }
}

resource "google_project_iam_policy" "project" {
  project     = "${var.id}"
  policy_data = "${data.google_iam_policy.policy.policy_data}"
  authoritative = true
}
```

This is actually all encapsulated within a generic module I have for managing GCP projects with Terraform. Sometimes I don't necessarily have any one that might be considered a viewer, so the member list might be empty. It'd be nice to be able to have behaviour exist where if the list of members is empty, the Terraform provider didn't even attempt to add it to to the payload.

(I'm not aware of any other way I could workaround this where the binding wouldn't be generated if the members list was empty, apart from generating my policies outside the module, specific to each project, and then passing them in - which I'd like to try avoid)

### Terraform Output

(Should provide enough valuable information as a debug log would provide)

```
  ~ google_project_iam_policy.project
      policy_data: "{\"bindings\":[{\"members\":[\"user:user@example.com\"],\"role\":\"roles/owner\"}]}" => "{\"bindings\":[{\"role\":\"roles/viewer\"},{\"members\":[\"user:user@example.com\"],\"role\":\"roles/owner\"}]}"
```

### Expected Behavior

No resources should have changed.

### Actual Behavior

The Terraform GCP provider is generating an empty binding without any members for `roles/viewer`, as can be seen in the output above. This means that on each plan/apply, the difference of what's returned from the GCP API and what's submitted do not match up, because GCP is obviously not storing the binding with no members.

### Steps to Reproduce

1. Take Terraform code above, substitute in own variables
2. Run `terraform apply` to apply
3. Run `terraform plan` and observe differences reported

### PR DESCRIPTION
**Pull request by ndmckinley**
Fixes #1338.

### CODE REVIEW

**Comment by ndmckinley** [comment]
```
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \                                    
        xargs -t -n4 go test  -timeout=30s -parallel=4                         
go test -timeout=30s -parallel=4 github.com/terraform-providers/terraform-provider-google github.com/terraform-providers/terraform-provider-google/google gith
ub.com/terraform-providers/terraform-provider-google/scripts
?       github.com/terraform-providers/terraform-provider-google        [no test files]
ok      github.com/terraform-providers/terraform-provider-google/google 0.117s
ok      github.com/terraform-providers/terraform-provider-google/scripts        0.016s
```

File: google/resource_google_project_iam_policy_test.go [hunk 1]
```diff
@@ -594,6 +594,7 @@ func TestIamMergeBindings(t *testing.T) {
 						"member-2",
 					},
 				},
+				{Role: "empty-role", Members: []string{}},
```
Comment (rosbo) [inline google/resource_google_project_iam_policy_test.go]: This seems like it needs to be formatted. Run go fmt before submitting

Comment (ndmckinley) [reply google/resource_google_project_iam_policy_test.go]: Nope, `go fmt` thinks it's okay.  `go vet` would complain otherwise and Travis would fail, right?

Comment (rosbo) [reply google/resource_google_project_iam_policy_test.go]: Yup. My bad. For some reason, I though a space would be required between `{` and `Role`.

You are good to go :)

**Comment by ndmckinley** [comment]
Only failures are existing failed tests, merging.

**Comment by Izlots** [comment]
I ran into a problem, maybe it is related somewhat to this binding change?


I want to create bindings based on the enabled services (stored in list local.services):
```
data "google_iam_policy" "my-project" {
<...>
  binding {
    members = [
      "${compact(list(contains(local.services, "compute.googleapis.com") ? "some-account" : ""))}",
    ]
    role = "roles/compute.serviceAgent"
  }
}
```

This results into a policy data like this:

```
{
  "bindings": [
  <...>
  {
    "role": "roles/compute.serviceAgent"
  },
  <...>
  ]
}
```

means the role is included, but does not contain any members part.

I tried this without convertsion `comptact(list(...))` in my google_iam_policy but then members could be filled with empty strings:

```
{
  "bindings": [
  <...>
  {
    "members": [
      ""
    ],
    "role": "roles/compute.serviceAgent"
  },
  <...>
  ]
}
```

terraform apply failes setting this policy data in both cases:

DEBUG Output / error message:
```
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4: {
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:   "error": {
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:     "code": 400,
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:     "message": "Request contains an invalid argument.",
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:     "errors": [
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:       {
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:         "message": "Request contains an invalid argument.",
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:         "domain": "global",
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:         "reason": "badRequest"
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:       }
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:     ],
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:     "status": "INVALID_ARGUMENT"
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4:   }
[DEBUG] plugin.terraform-provider-google_v1.14.0_x4: }
```

**Comment by ndmckinley** [comment]
Sorry for the inconvenience!

To make sure I understand, you're saying that your use case requires that Terraform not filter out empty members lists client-side before sending the request to GCP?  That's what this PR does.

After this PR, your example should not send a request including `roles/compute.serviceAgent` (unless another binding also has that role).  Could you include a little bit more debug information so I can see the request that got sent?

```
{
  "bindings": [
  <...>
  {
    "role": "roles/compute.serviceAgent"
  },
  <...>
  ]
}
```
Should be equivalent to
```
{
  "bindings": [
  <...>
  ]
}
```
as if the binding with no members wasn't present at all.

**Comment by Izlots** [comment]
Sorry for the late response. I somewhat missed the noftification.

My use case is: I have a module with some true/false switches to enable or disable certain services within a project. I also want to use `google_project_iam_policy` to maintain the projects IAM settings. I don't have any other IAM polcy related ressources within the module (or anywhere else).
Depending on the enabled / disabled services several service accounts should or should not be present within the IAM policy data:

```
  binding {
    members = [
      "${compact(list(contains(local.services, "compute.googleapis.com") ? format(local.fmt_srvacc_compute_system,
        element(google_project.workbench.*.number, count.index)) : ""))}",
    ]

    role = "roles/compute.serviceAgent"
  }
```

So my local variable services holds all enabled services, and if compute is in there (is enabled) I need to grant role compute.serviceAgent to the compute service account.

terraform apply output:

```
  + module.cschroer3.google_project_iam_policy.workbench
      id:             <computed>
      etag:           <computed>
      policy_data:    "{\"bindings\":[{\"role\":\"roles/dataproc.editor\"},{\"role\":\"roles/compute.serviceAgent\"},{\"role\":\"roles/container.serviceAgent\"},{\"role\":\"roles/dataflow.serviceAgent\"},{\"members\":[\"\",\"serviceAccount:******@cloudservices.gserviceaccount.com\"],\"role\":\"roles/editor\"},{\"members\":[\"serviceAccount:automatisation@****.iam.gserviceaccount.com\"],\"role\":\"roles/owner\"},{\"members\":[\"user:christian.schroer@****.com\"],\"role\":\"roles/viewer\"},{\"role\":\"roles/dataproc.serviceAgent\"}]}"
      project:        "******"
      restore_policy: <computed>
```

Or in better readable JSON:
```
{
  "bindings": [
    {
      "role": "roles/dataproc.editor"
    },
    {
      "role": "roles/compute.serviceAgent"
    },
    {
      "role": "roles/container.serviceAgent"
    },
    {
      "role": "roles/dataflow.serviceAgent"
    },
    {
      "members": [
        "",
        "serviceAccount:******@cloudservices.gserviceaccount.com"
      ],
      "role": "roles/editor"
    },
    {
      "members": [
        "serviceAccount:automatisation@****.iam.gserviceaccount.com"
      ],
      "role": "roles/owner"
    },
    {
      "members": [
        "user:christian.schroer@****.com"
      ],
      "role": "roles/viewer"
    },
    {
      "role": "roles/dataproc.serviceAgent"
    }
  ]
}
```

You see I have multiple roles which may be present or may not be present depending on the enabled services within the project. I was expecting this change to make this possible, as the members list is somewhat empty, so terraform should not include that role.

Maybe it’s related to my `compact(list(…))` hack to work around some limitations with the conditional operator?

**Comment by Izlots** [comment]
Hey @ndmckinley any news on this? Anything I can help you with?

**Comment by ndmckinley** [comment]
I missed your update, sorry about that.  I see an empty string there in your `members` list for `roles/editor` - is that in the real input?  That would cause a 400.

**Comment by Izlots** [comment]
Hey, yeah, that's the issue. I was so focused on the role bindings without members, I just didn't saw it. So this works as it should, sorry for my false report.

Thanks a lot.
