### PR TITLE
Change authorized_networks to a Set

### LINKED ISSUE #547: SQL instance's authorized_networks constantly shifting order
### Terraform Version
v0.10.7

### Affected Resource(s)
google_sql_database_instance

### Terraform Configuration Files
```hcl
variable "environment"     { }
variable "application"     { default = "intervention" }
variable "region"          { default = "us-east1"     }
variable "region_zone"     { default = "us-east1-b"   }
variable "project_id"      { }


terraform {
  backend "gcs" {
    bucket  = "intervention-terraform"
    path    = "intervention/terraform.tfstate"
  }
}

provider "google" {
  project     = "${var.project_id}"
  region      = "${var.region}"
  version     = "1.0.1"
}

resource "google_compute_address" "intervention-address" {
  name = "intervention-address"
}

resource "google_compute_instance" "intervention" {
  tags         = ["intervention-host"]
  name         = "${var.application}"
  machine_type = "n1-standard-1"
  zone         = "${var.region_zone}"

  boot_disk {
    initialize_params {
      image = "ubuntu-1604-lts"
      type  = "pd-standard"
    }
  }

  network_interface {
    network = "default"

    access_config {
      nat_ip = "${google_compute_address.intervention-address.address}"
    }
  }

  service_account {
    scopes = ["https://www.googleapis.com/auth/logging.write"]
  }
}

resource "random_id" "name_suffixes" {
  byte_length = 4
}

resource "google_sql_database_instance" "sql_database_instance" {
  name             = "${var.environment}-${var.application}-${random_id.name_suffixes.hex}"
  region           = "${var.region}"
  database_version = "POSTGRES_9_6"

  settings {
    tier      = "db-g1-small"
    disk_type = "PD_SSD"

    ip_configuration {
      authorized_networks {
        name = "${var.application}"
        value = "${google_compute_instance.intervention.network_interface.0.access_config.0.nat_ip}"
      }
      authorized_networks {
        name = "stitchdata-1"
        value = "52.23.137.21/32"
      }
      authorized_networks {
        name = "stitchdata-2"
        value = "52.204.223.208/32"
      }
      authorized_networks {
        name = "stitchdata-3"
        value = "52.204.228.32/32"
      }
      authorized_networks {
        name = "stitchdata-4"
        value = "52.204.230.227/32"
      }
      authorized_networks {
        name = "stitchdata-5"
        value = "54.88.76.97/32"
      }
      authorized_networks {
        name = "webster-pl-tmobile"
        value = "178.180.0.0/16"
      }
    }

    backup_configuration {
      enabled = true
      start_time = "01:00"
    }

    location_preference {
      zone = "${var.region_zone}"
    }

    maintenance_window {
      day          = 6
      hour         = 1
      update_track = "stable"
    }
  }
}

resource "google_sql_database" "sql_database" {
  name     = "intervention"
  instance = "${google_sql_database_instance.sql_database_instance.name}"
}

resource "google_sql_user" "users_root" {
  name     = "root"
  instance = "${google_sql_database_instance.sql_database_instance.name}"
  host     = ""
  password = "NOT GONNA GIVE YOU THAT"
}

resource "google_sql_user" "users_stitchdata" {
  name     = "stitchdata"
  instance = "${google_sql_database_instance.sql_database_instance.name}"
  host     = ""
  password = "NOT GONNA GIVE YOU THAT"
  project  = "${var.project_id}"
}
```

### Debug Output
https://gist.github.com/anonymous/a8baf57441aa6c1e158dc9ee5a30c54c

### Expected Behavior
After running `terraform apply`, running `terraform plan` reports nothing to update.

### Actual Behavior
After running `terraform apply`, running `terraform plan` reports that the list of authorized_networks on the SQL server needs to be updated. The set of IPs and their names doesn't change, actually. But terraform wants to put them in different order every single time, for some reason.

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

### PR DESCRIPTION
**Pull request by rosbo**
Fixes #547 without changing the behavior of the update method (old style behavior where it tried as hard as possible to preserve changes that happened outside of Terraform, see #564).

### CODE REVIEW

File: google/resource_sql_database_instance.go [hunk 1]
```diff
@@ -128,24 +145,10 @@ func resourceSqlDatabaseInstance() *schema.Resource {
...
-													Type:     schema.TypeString,
-													Optional: true,
-												},
-												"value": &schema.Schema{
-													Type:     schema.TypeString,
-													Optional: true,
-												},
-											},
-										},
+										Set:      schema.HashResource(sqlDatabaseAuthorizedNetWorkSchemaElem),
```
Comment (danawillow) [inline google/resource_sql_database_instance.go]: This is actually the default behavior, so you don't need this line (I'm fine either way if you want to leave it in to be explicit).

I do wonder whether it actually makes more sense to hash on something a bit more like a primary key, like the network value. Even though our update logic will be the same no matter which part of it changes, it's possible that someone could get confused if they see in a plan that the whole thing is changing rather than just the part of it they changed. What do you think?

Comment (rosbo) [reply google/resource_sql_database_instance.go]: I made it explicit because below (line 1056), we need to pass the hash function for the NewSet method and by making it explicit here, it is easier to see that both uses the same method.

The API does accept:
```
      authorized_networks {
        name = "stitchdata-3"
        value = "52.204.228.32/32"
        expiration_time = "2018-08-30T13:22:53.108Z"
      }
      authorized_networks {
        name = "stitchdata-3"
        value = "52.204.228.32/32"
        expiration_time = "2018-07-21T13:22:53.108Z"
      }
```

and keeps both entries...

Since the primary key used by the API is all three fields, I suggest we stick to the same key. If we don't, we would be more restrictive than the API which could prevent reasonable use cases that we are not necessary aware of.

**Comment by rosbo** [comment]
```sh
--- PASS: TestAccGoogleSqlDatabaseInstance_settings_basic (40.81s)
--- PASS: TestAccGoogleSqlDatabaseInstance_importBasic (50.12s)
--- PASS: TestAccGoogleSqlDatabaseInstance_basic (59.57s)
--- PASS: TestAccGoogleSqlDatabaseInstance_authNets (73.12s)
--- PASS: TestAccGoogleSqlDatabaseInstance_multipleOperations (74.13s)
--- PASS: TestAccGoogleSqlDatabaseInstance_basic2 (60.89s)
--- PASS: TestAccGoogleSqlDatabaseInstance_settings_downgrade (45.03s)
--- PASS: TestAccGoogleSqlDatabaseInstance_settings_upgrade (65.79s)
--- PASS: TestAccGoogleSqlDatabaseInstance_diskspecs (377.40s)
--- PASS: TestAccGoogleSqlDatabaseInstance_basic3 (419.98s)
--- PASS: TestAccGoogleSqlDatabaseInstance_importBasic3 (398.40s)
--- PASS: TestAccGoogleSqlDatabaseInstance_maintenance (459.13s)
--- PASS: TestAccGoogleSqlDatabaseInstance_dontDeleteDefaultUserOnReplica (644.16s)
--- PASS: TestAccGoogleSqlDatabaseInstance_slave (951.12s)
```

**Comment by danawillow** [comment]
GitHub appears to have eaten @rosbo's comment but it said:
> I made it explicit because below (line 1056), we need to pass the hash function for the NewSet method and by making it explicit here, it is easier to see that both uses the same method.
>
>The API does accept:
```
      authorized_networks {
        name = "stitchdata-3"
        value = "52.204.228.32/32"
        expiration_time = "2018-08-30T13:22:53.108Z"
      }
      authorized_networks {
        name = "stitchdata-3"
        value = "52.204.228.32/32"
        expiration_time = "2018-07-21T13:22:53.108Z"
      }
```
>and keeps both entries...
>
>Since the primary key used by the API is all three fields, I suggest we stick to the same key. If we don't, we would be more restrictive than the API which could prevent reasonable use cases that we are not necessary aware of.

**Comment by danawillow** [comment]
Looks like tests are failing in CI, can you take a look?

```

------- Stdout: -------
=== RUN   TestAccGoogleSqlDatabaseInstance_authNets
--- FAIL: TestAccGoogleSqlDatabaseInstance_authNets (50.86s)
    testing.go:434: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: google_sql_database_instance.instance
          settings.0.ip_configuration.0.authorized_networks.#:                          "0" => "1"
          settings.0.ip_configuration.0.authorized_networks.3898304677.expiration_time: "" => "2017-11-15T16:19:00.094Z"
          settings.0.ip_configuration.0.authorized_networks.3898304677.name:            "" => "misc"
          settings.0.ip_configuration.0.authorized_networks.3898304677.value:           "" => "108.12.12.12"
        
        STATE:
        
        google_sql_database_instance.instance:
          ID = tf-lw-1398641235381731251
          connection_name = hc-terraform-testing:tf-lw-1398641235381731251
          database_version = MYSQL_5_6
          ip_address.# = 1
          ip_address.0.ip_address = 173.194.104.164
          ip_address.0.time_to_retire = 
          master_instance_name = 
          name = tf-lw-1398641235381731251
          region = us-central
          replica_configuration.# = 0
          self_link = https://www.googleapis.com/sql/v1beta4/projects/hc-terraform-testing/instances/tf-lw-1398641235381731251
          settings.# = 1
          settings.0.activation_policy = ON_DEMAND
          settings.0.authorized_gae_applications.# = 0
          settings.0.backup_configuration.# = 1
          settings.0.backup_configuration.0.binary_log_enabled = false
          settings.0.backup_configuration.0.enabled = false
          settings.0.backup_configuration.0.start_time = 08:00
          settings.0.crash_safe_replication = false
          settings.0.database_flags.# = 0
          settings.0.disk_autoresize = false
          settings.0.disk_size = 0
          settings.0.disk_type = 
          settings.0.ip_configuration.# = 1
          settings.0.ip_configuration.0.authorized_networks.# = 0
          settings.0.ip_configuration.0.ipv4_enabled = true
          settings.0.ip_configuration.0.require_ssl = false
          settings.0.location_preference.# = 0
          settings.0.maintenance_window.# = 0
          settings.0.pricing_plan = PER_USE
          settings.0.replication_type = SYNCHRONOUS
          settings.0.tier = D0
          settings.0.version = 1
FAIL
```

**Comment by danawillow** [comment]
Although weirdly it looks like this didn't start failing until last night, so it might actually just be a coincidence.

**Comment by rosbo** [comment]
Looking into it

**Comment by rosbo** [comment]
I found the issue, there is an expiration time set in the test and the date is `expiration_time = "2017-11-15T16:19:00.094Z"` (yesterday)

**Comment by rosbo** [comment]
Fix is here: #754
