### PR TITLE
dns: Add special handling for ns records.

### LINKED ISSUE #95: Cannot Manage Google Cloud DNS NS Records
_This issue was originally opened by @j0sh3rs as hashicorp/terraform#14796. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

When Terraform creates a google_dns_managed_zone, the zone automatically gets created with NS records specific to Google Cloud (nameservers they provide that the zone will live on).  Terraform does not import these NS records into state, so all future attempts to add or manipulate NS records in any Google Cloud Zone will fail, citing that the record set already exists:
```
* google_dns_record_set.clouddns_ns: Error creating DNS RecordSet: googleapi: Error 409: The resource 'entity.change.additions[0]' named 'domain.com. (NS)' already exists, alreadyExists
```

### Terraform Version
```
$ terraform -v
Terraform v0.9.5
```
### Affected Resource(s)
Please list the resources as a list, for example:
- google_dns_managed_zone
- google_dns_record_set

### Terraform Configuration Files
```
resource "google_dns_managed_zone" "public" {
  name        = "domain-name"
  dns_name    = "domain.com."
  description = "domain.com"
}

resource "google_dns_record_set" "clouddns_ns" {
  count = "${var.type == "NS" ? 1 : 0}"
  name = "${var.name == "" ? format("%v.", var.domain) : format("%v.%v.",var.name,var.domain)}"
  type = "${var.type}"
  ttl  = "${var.ttl}"

  managed_zone = "${replace(var.domain, ".", "-")}"

  rrdatas = ["${formatlist("%v.", var.value)}"]
}

module "domain-com-NS" {
  source = "../../modules/pub_dns_record"
  domain = "domain.com"
  name   = ""
  type   = "NS"
  value  = ["ns1.example.com", "ns2.example.com"]
  ttl    = "172800"
}
```

### Expected Behavior
Terraform should either automatically import the NS records into state for management, or provide some method for managing them

### Actual Behavior
NS records are completely unmanageable and must be manually adjusted

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This generally applies to all GCE zone sets, not just to ones Terraform creates

### PR DESCRIPTION
**Pull request by paddycarver**
Cloud DNS requires every managed zone to have an NS record at all times.
This means if people want to manage their own NS records, we need to add
their new record and remove the old one in the same call. It also means
we can't delete NS records, as we wouldn't know what to replace it with.
So deleting of NS records short-circuits. For the case of `terraform
destroy`, this prevents the error. It does mean if the user explicitly
tries to remove their NS zone from their project, it silently does
nothing, but that's unavoidable unless we want to A) restore a default
value (and it looks like the default values change from zone to zone?
And that is arguably just as unexpected?) or B) let the (arguably more
reasonable) `terraform destroy` case be impossible.

Fixes #95.

### CODE REVIEW

File: google/resource_dns_record_set.go [hunk 1]
```diff
@@ -77,6 +77,25 @@ func resourceDnsRecordSetCreate(d *schema.ResourceData, meta interface{}) error
 		},
 	}
 
+	if d.Get("type").(string) == "NS" {
+		log.Printf("{DEBUG] DNS record list request for %q", zone)
```
Comment (catsby) [inline google/resource_dns_record_set.go]: typo `{` instead of `[`

File: google/resource_dns_record_set.go [hunk 2]
```diff
@@ -135,6 +154,13 @@ func resourceDnsRecordSetRead(d *schema.ResourceData, meta interface{}) error {
 }
 
 func resourceDnsRecordSetDelete(d *schema.ResourceData, meta interface{}) error {
+
+	// NS records must always have a value, so we short-circuit delete
+	// this allows terraform delete to work, but may have unexpected
+	// side-effects when deleting just that record set.
+	if d.Get("type").(string) == "NS" {
```
Comment (catsby) [inline google/resource_dns_record_set.go]: Let's put a `[DEBUG]` log here; Terraform is doing something "unexpected", or otherwise lying to people, so let's tell them that we aren't doing X because of Y, and link to some documentation. Either Google's or preferably some kind of `NOTE` on https://www.terraform.io/docs/providers/google/r/dns_record_set.html that explains the what and why here.

**Comment by danawillow** [comment]
@paddycarver, what's the status on this?

**Comment by paddycarver** [comment]
Sorry for the delay on this, believe I've addressed all the comments.

File: google/resource_dns_record_set.go [hunk 3]
```diff
@@ -77,6 +77,25 @@ func resourceDnsRecordSetCreate(d *schema.ResourceData, meta interface{}) error
 		},
 	}
 
+	if d.Get("type").(string) == "NS" {
```
Comment (danawillow) [inline google/resource_dns_record_set.go]: Can you add a comment explaining why this section needs to happen? (even just a link to the docs is probably fine)

**Comment by paddycarver** [comment]
@danawillow just updated with the comment. Good to merge?

**Comment by danawillow** [comment]
Yup
