### PR TITLE
Fix crash when updating container cluster resource labels.

### LINKED ISSUE #1767: Terraform crash on google_container_cluster
### Terraform Version
```
Terraform v0.11.7
+ provider.google v1.16.0
+ provider.local v1.1.0
```

### Affected Resource(s)
- google_container_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "google" {
  credentials = "${file("/etc/gcp/gke-manager")}"
  project     = "bolcom-frieps6"
  region      = "europe-west4"
}

resource "google_container_cluster" "bolcom-sbx-89s" {
  name               = "bolcom-sbx-89s"
  region             = "europe-west4"
  project            = "bolcom-frieps6"
  min_master_version = "1.10.4-gke.2"
  enable_legacy_abac = false
  network            = "bolcom-sbx"
  subnetwork         = "bolcom-sbx-europe-west4"


  master_auth {
    username =""
    password =""
  }

  addons_config {
    http_load_balancing {
      disabled = false
    }
    horizontal_pod_autoscaling {
      disabled = false
    }
    kubernetes_dashboard {
      disabled = true
    }
    network_policy_config {
      disabled = false
    }
  }

  network_policy {
    provider = "CALICO"
    enabled = true
  }

  pod_security_policy_config {
    enabled = true
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "02:00"
    }
  }

  ip_allocation_policy {
    cluster_secondary_range_name = "bolcom-sbx-89s-pods"
    services_secondary_range_name = "bolcom-sbx-89s-services"
  }

  master_ipv4_cidr_block = "172.16.0.16/28"
  private_cluster        = true

  master_authorized_networks_config {
    cidr_blocks = [
      { cidr_block = "91.195.1.40/30", display_name = "office" },
      { cidr_block = "185.14.171.68/32", display_name = "shd-gcp-jump-001" },
      { cidr_block = "185.14.168.100/30", display_name = "vpn-005-006-007-008" },
    ]
  }

  node_pool {
    name       = "internal"
    initial_node_count = 1

    autoscaling {
      min_node_count = 1
      max_node_count = 5
    }

    management {
      auto_repair = true
      auto_upgrade = true
    }
    node_config {
      preemptible = true
      disk_size_gb = 500
      machine_type = "n1-standard-1"
      service_account = "bolcom-sbx-89s-sa@bolcom-frieps6.iam.gserviceaccount.com"
      tags = ["bolcom-sbx-89s-internal"]

      labels {
        bol-environment = "sbx",
        bol-opex = "teamprovisioning",
        bol-status = "operational",
      }

      workload_metadata_config {
        node_metadata = "SECURE"
      }
    }
  }
}
resource "local_file" "master_bolcom-sbx-89s_ip_fact" {
  content = "bol_kubernetes_instance_bolcom-sbx-89s_master_ip=${google_container_cluster.bolcom-sbx-89s.endpoint}"
  filename = "/data/bolcom-frieps6/puppet-executor-data/var/facts.d/kubernetes_instance_bolcom-sbx-89s_master_ip.txt"
}

resource "local_file" "master_bolcom-sbx-89s_cluster_ca" {
  content="${base64decode(google_container_cluster.bolcom-sbx-89s.master_auth.0.cluster_ca_certificate)}"
  filename = "/data/bolcom-frieps6/puppet-executor-data/kubernetes_clusters/bolcom-sbx-89s/cluster.ca"
}

resource "local_file" "cluster_bolcom-sbx-89s_additional_zones_fact" {
  content = "bol_kubernetes_instance_bolcom-sbx-89s_additional_zones=${jsonencode(google_container_cluster.bolcom-sbx-89s.additional_zones)}"
  filename = "/data/bolcom-frieps6/puppet-executor-data/var/facts.d/kubernetes_instance_bolcom-sbx-89s_additional_zones.txt"
}
```

### Panic Output
See https://gist.github.com/wmuizelaar/8fdddb7e42aac6eade2800308d530fed

### Expected Behavior
The defined cluster would have been kept intact and unchanged

### Actual Behavior
Terraform crashed, and the state got screwed up.

### Steps to Reproduce
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1663

### PR DESCRIPTION
**Pull request by paddycarver**
We had a bad type coercion in the code to update container cluster
resource labels. This fixes the coercion.

We didn't notice this because there was no test exercising the update
code path. I've added the test, which reproduced the panic before this
PR was applied and passes successfully now that the coercion is fixed.

Fixes #1767.

### CODE REVIEW

File: google/resource_container_cluster.go [hunk 1]
```diff
@@ -1145,7 +1145,11 @@ func resourceContainerClusterUpdate(d *schema.ResourceData, meta interface{}) er
 	}
 
 	if d.HasChange("resource_labels") {
-		resourceLabels := d.Get("resource_labels").(map[string]string)
+		resourceLabelsI := d.Get("resource_labels").(map[string]interface{})
```
Comment (ndmckinley) [inline google/resource_container_cluster.go]: Think we have this in `utils.go` - `convertStringMap`.

https://github.com/terraform-providers/terraform-provider-google/blob/master/google/utils.go#L286
