### PR TITLE
Changed google_compute_instance_group_manager target_size default to 0.

### LINKED ISSUE #13: in google_compute_instance_group_manager if target_size is set to 0 value get ignored
Hi there,

In `google_compute_instance_group_manager` if you set `target_size` to 0 the value get ignored and the default value of 1 get applied at the first apply. Similar issue when you try to change the value from a non zero value to zero. Terraform will detect the change however when applying the plan the value will not got changed to 0.

### Terraform Version
- terraform v0.96
- terraform v0.97
- terraform v0.98

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance_group_manager

### Terraform Configuration Files
```hcl
resource "google_compute_instance_template" "template" {
  name_prefix = "template-server"

  region = "${var.region}"

  lifecycle {
    create_before_destroy = true
  }

  network_interface {
    network = "default"
  }

  machine_type         = "f1-micro"
  can_ip_forward       = false

  scheduling {
    automatic_restart   = true
    on_host_maintenance = "TERMINATE"
  }

  // Create a new boot disk from an image
  disk {
    source_image = "projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20170516"
    disk_type    = "pd-ssd"
    auto_delete  = true
    boot         = true
  }


  service_account {
    scopes = [ ]
  }

}

resource "google_compute_instance_group_manager" "group_manager" {
  name        = "instance-group-tf-bug"

  base_instance_name = "servers"
  instance_template  = "${google_compute_instance_template.template.self_link}"
  update_strategy    = "NONE"

  zone        = "us-central1-a"
  target_size = 0
}
```

### Debug Output
```
google_compute_instance_group_manager.group_manager: Creating...
  base_instance_name: "" => "servers"
  fingerprint:        "" => "<computed>"
  instance_group:     "" => "<computed>"
  instance_template:  "" => "https://www.googleapis.com/compute/v1/projects/cloud-staging-168820/global/instanceTemplates/template-server0028f8764b2b18e1b29f3ea74a"
  name:               "" => "instance-group-tf-bug"
  project:            "" => "<computed>"
  self_link:          "" => "<computed>"
  target_size:        "" => "0"
  update_strategy:    "" => "NONE"
  zone:               "" => "us-central1-a"
```

### Expected Behavior
Inttance group number of instances should be 0 and no instances should be created.

### Actual Behavior
Instance group number of instances is 1

### Steps to Reproduce
1. `terraform apply`

### PR DESCRIPTION
**Pull request by rileykarson**
Set the default target_size to 0 so that target sizes of 0 don't get set as the old default of 1. Existing configurations won't change as a result of changing the default, since the field is computed.

This is not a breaking change for existing configurations; resources with no value set will stay at their current setting. Scripts that rely on the old default of 1 at creation time will need to be updated.

Fixes #13 
@danawillow

### CODE REVIEW

**Comment by rileykarson** [comment]
Related: https://github.com/hashicorp/terraform/issues/5694 tracks the ability to both have a default of 1 + allow 0 values for this field.

File: google/resource_compute_instance_group_manager.go [hunk 1]
```diff
@@ -256,7 +256,6 @@ func resourceComputeInstanceGroupManagerRead(d *schema.ResourceData, meta interf
 	d.Set("named_port", flattenNamedPorts(manager.NamedPorts))
 	d.Set("fingerprint", manager.Fingerprint)
 	d.Set("instance_group", manager.InstanceGroup)
-	d.Set("target_size", manager.TargetSize)
```
Comment (danawillow) [inline google/resource_compute_instance_group_manager.go]: This was removed because it could change with the autoscaler, right? If so mind adding a comment of that nature?

File: google/resource_compute_instance_group_manager.go [hunk 2]
```diff
@@ -132,18 +132,18 @@ func resourceComputeInstanceGroupManagerCreate(d *schema.ResourceData, meta inte
 		return err
 	}
 
-	// Get group size, default to 1 if not given
-	var target_size int64 = 1
+	var targetSize int64 = 0
```
Comment (danawillow) [inline google/resource_compute_instance_group_manager.go]: targetSize := 0

File: google/resource_compute_instance_group_manager.go [hunk 3]
```diff
@@ -132,18 +132,18 @@ func resourceComputeInstanceGroupManagerCreate(d *schema.ResourceData, meta inte
...
 	}
 
 	// Build the parameter
 	manager := &compute.InstanceGroupManager{
 		Name:             d.Get("name").(string),
 		BaseInstanceName: d.Get("base_instance_name").(string),
 		InstanceTemplate: d.Get("instance_template").(string),
-		TargetSize:       target_size,
+		TargetSize:       targetSize,
+		ForceSendFields:  []string{"TargetSize"},
```
Comment (danawillow) [inline google/resource_compute_instance_group_manager.go]: might be nice to have a comment here like "Force send TargetSize to allow it to have a value of 0"

File: google/resource_compute_instance_group_manager.go [hunk 4]
```diff
@@ -382,23 +381,19 @@ func resourceComputeInstanceGroupManagerUpdate(d *schema.ResourceData, meta inte
 		d.SetPartial("named_port")
 	}
 
-	// If size changes trigger a resize
+	// We won't ever see changes if target_size is unset
```
Comment (danawillow) [inline google/resource_compute_instance_group_manager.go]: I'm not quite sure what this comment is trying to tell me

File: google/resource_compute_instance_group_manager.go [hunk 5]
```diff
@@ -382,23 +381,19 @@ func resourceComputeInstanceGroupManagerUpdate(d *schema.ResourceData, meta inte
...
-		if v, ok := d.GetOk("target_size"); ok {
-			// Only do anything if the new size is set
-			target_size := int64(v.(int))
-
-			op, err := config.clientCompute.InstanceGroupManagers.Resize(
-				project, d.Get("zone").(string), d.Id(), target_size).Do()
-			if err != nil {
-				return fmt.Errorf("Error updating InstanceGroupManager: %s", err)
-			}
+		target_size := int64(d.Get("target_size").(int))
```
Comment (danawillow) [inline google/resource_compute_instance_group_manager.go]: targetSize

File: google/resource_compute_instance_group_manager_test.go [hunk 6]
```diff
@@ -39,6 +39,32 @@ func TestAccInstanceGroupManager_basic(t *testing.T) {
 	})
 }
 
+func TestAccInstanceGroupManager_targetSizeZero(t *testing.T) {
+	var manager compute.InstanceGroupManager
+
+	template := fmt.Sprintf("igm-test-%s", acctest.RandString(10))
```
Comment (danawillow) [inline google/resource_compute_instance_group_manager_test.go]: optional nit: templateName, igmName

File: website/docs/r/compute_instance_group_manager.html.markdown [hunk 7]
```diff
@@ -74,9 +74,9 @@ The following arguments are supported:
     restart all of the instances at once. In the future, as the GCE API matures
     we will support `"ROLLING_UPDATE"` as well.
 
-* `target_size` - (Optional) If not given at creation time, this defaults to 1.
-    Do not specify this if you are managing the group with an autoscaler, as
-    this will cause fighting.
+* `target_size` - (Optional, Default `0`) The target number of running instances for this managed
```
Comment (danawillow) [inline website/docs/r/compute_instance_group_manager.html.markdown]: Do we normally put the default in that spot? I don't necessarily have a problem with it, but I think normally we just put it in the description.

File: google/resource_compute_instance_group_manager.go (hunk 2 above)
Comment (rileykarson) [inline google/resource_compute_instance_group_manager.go]: Go is convinced this is an `int`, not `int64` with that syntax; using `targetSize := int64(0)`

File: google/resource_compute_instance_group_manager.go (hunk 3 above)
Comment (rileykarson) [inline google/resource_compute_instance_group_manager.go]: Done.

File: google/resource_compute_instance_group_manager.go (hunk 1 above)
Comment (rileykarson) [inline google/resource_compute_instance_group_manager.go]: It was getting set twice before, the other d.Set is just out of view here.

File: google/resource_compute_instance_group_manager.go (hunk 4 above)
Comment (rileykarson) [inline google/resource_compute_instance_group_manager.go]: Removed.

File: google/resource_compute_instance_group_manager.go (hunk 5 above)
Comment (rileykarson) [inline google/resource_compute_instance_group_manager.go]: Done.

File: google/resource_compute_instance_group_manager_test.go (hunk 6 above)
Comment (rileykarson) [inline google/resource_compute_instance_group_manager_test.go]: Done.

File: website/docs/r/compute_instance_group_manager.html.markdown (hunk 7 above)
Comment (rileykarson) [inline website/docs/r/compute_instance_group_manager.html.markdown]: We use that style in a few places, I think I happened to have seen one of those right before writing this. Updated.

File: google/resource_compute_instance_group_manager.go (hunk 1 above)
Comment (danawillow) [inline google/resource_compute_instance_group_manager.go]: boooo github

**Comment by danawillow** [comment]
```
TF_ACC=1 go test ./google -v -run=TestAccInstanceGroupManager -timeout 120m
=== RUN   TestAccInstanceGroupManager_importBasic
--- PASS: TestAccInstanceGroupManager_importBasic (253.35s)
=== RUN   TestAccInstanceGroupManager_importUpdate
--- PASS: TestAccInstanceGroupManager_importUpdate (263.10s)
=== RUN   TestAccInstanceGroupManager_basic
--- PASS: TestAccInstanceGroupManager_basic (222.92s)
=== RUN   TestAccInstanceGroupManager_targetSizeZero
--- PASS: TestAccInstanceGroupManager_targetSizeZero (46.14s)
=== RUN   TestAccInstanceGroupManager_update
--- PASS: TestAccInstanceGroupManager_update (288.82s)
=== RUN   TestAccInstanceGroupManager_updateLifecycle
--- PASS: TestAccInstanceGroupManager_updateLifecycle (114.07s)
=== RUN   TestAccInstanceGroupManager_updateStrategy
--- PASS: TestAccInstanceGroupManager_updateStrategy (231.41s)
=== RUN   TestAccInstanceGroupManager_separateRegions
--- PASS: TestAccInstanceGroupManager_separateRegions (231.78s)
PASS
```
